---
title: "625 Trend"
author: "Longfei Zhang"
date: "12/5/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(timeDate)
library(readr)
library(parallel)
library(dplyr)
library(ggplot2)
library(tidyr)
```


```{r read data}
mydata <- read_csv('C:/Users/ZLF/Documents/Iowa_Data.csv', show_col_types = FALSE)
```


```{r transform date}
mydata$mydate <- unclass(as.Date(mydata$Date, format = '%m/%d/%Y'))
mydata$mydate <- mydata$mydate-min(mydata$mydate)+1
```

```{r calculate profit}
mydata <- mydata%>%
  group_by(Item.Number) %>%
  mutate(State.Bottle.Retail=mean(State.Bottle.Retail)) %>%
  mutate(State.Bottle.Cost=mean(State.Bottle.Cost)) %>%
  mutate(Profit=(State.Bottle.Retail-State.Bottle.Cost)*Bottles.Sold)
```

```{r calculate total profit for each item}
total_profit <- mydata %>% group_by(Item.Number) %>%
              mutate(tol_profit=sum(Profit)/1e6) %>%
              mutate(botl_profit=State.Bottle.Retail-State.Bottle.Cost) %>%
              distinct(Item.Number, tol_profit, botl_profit, State.Bottle.Cost) %>%
              filter(botl_profit>0) %>%
              filter(botl_profit<60) %>%
              arrange(desc(tol_profit), desc(botl_profit))
```



```{r total profit against bottle cost plot}
p_plot <- ggplot(total_profit, aes(State.Bottle.Cost, tol_profit)) + geom_point(size = 1) + labs(title = 'Total Profit Plot', x = 'Bottle Cost (USD)', y = 'Total Profit (MUSD)')
p_plot
```

```{r extract top 10}
top10 <- total_profit[1:10, ]
```


```{r calculate profit by day}
profit_date <- mydata %>% group_by(Item.Number, mydate) %>%
              mutate(p=sum(Profit)) %>%
              distinct(Item.Number, mydate, p)
```



```{r calculate weekly profit for each liquor in top 10}
trend <- matrix(0, nrow = 209, ncol = 11)
trend[, 1] <- 1:209
colnames(trend) <- c('week', top10$Item.Number)
for(i in 1:10){
  tmp <- profit_date %>%
    filter(Item.Number==top10$Item.Number[i]) %>%
    ungroup %>%
    mutate(week=rep(1:209, each=7)[mydate]) %>%
    add_row(week = 1:209, p = 0) %>%
    group_by(week) %>% 
    mutate(week_p = sum(p)/1e3) %>%
    distinct(week, week_p) %>%
    arrange(week)
  trend[, i+1] <- as.vector(tmp$week_p)
}
```


```{r map trend for each top 10 liquor}
trend.df <- as.data.frame(trend)
trend.df <- trend.df %>% pivot_longer(-week)
trend_plot <- ggplot(trend.df) + geom_smooth(aes(week,value,colour=name), method = 'loess', se = FALSE, formula = y~x) +labs(title = 'Top 10 Week Profit Trend', x = 'Week', y = 'Week Profit (kUSD)')
trend_plot
```


```{r map total trend}
tot.trend <- profit_date %>%
    ungroup %>%
    mutate(week=rep(1:209, each=7)[mydate]) %>%
    add_row(week = 1:209, p = 0) %>%
    group_by(week) %>% 
    mutate(week_p = sum(p)/1e6) %>%
    distinct(week, week_p) %>%
    arrange(week)
tot.trend_plot <- ggplot(tot.trend) + geom_smooth(aes(week, week_p), method = 'loess', se = FALSE, formula = y~x) + labs(title = 'Total Week Profit Trend', x = 'Week', y = 'Total Week Profit (MUSD)')
tot.trend_plot
```


```{r check category}
tmp <- mydata %>% 
      distinct(Category, Item.Number) %>%
      group_by(Category) %>%
      count(Category)
tmp <- tmp[order(tmp$n, decreasing = T), ]
tmp
```

```{r generate sales data by week and by month}
sales_week <- mydata %>% 
              group_by(mydate) %>%
              mutate(p=sum(Sale..Dollars.)) %>%
              distinct(mydate, p) %>%
              ungroup %>%
              mutate(week=rep(1:209, each=7)[mydate]) %>%
              add_row(week = 1:209, p = 0) %>%
              group_by(week) %>% 
              mutate(week_p = sum(p)/1e6) %>%
              distinct(week, week_p) %>%
              arrange(week)

sales_month <- mydata %>% 
              group_by(mydate) %>%
              mutate(p=sum(Sale..Dollars.)) %>%
              distinct(mydate, p) %>%
              ungroup %>%
              mutate(month=rep(1:49, each=30)[mydate]) %>%
              add_row(month = 1:49, p = 0) %>%
              group_by(month) %>% 
              mutate(month_p = sum(p)/1e6) %>%
              distinct(month, month_p) %>%
              arrange(month)
```

```{r my regression function to calculate covid index}
myweek <- 1:104
meanX <- mean(myweek)
SSX <- sum((myweek-meanX)^2)

mylm <- function(sale, date){
  sale1 <- sale[date<105]
  date1 <- date[date<105]
  b1 <- sum(sale1*(date1-meanX))/SSX
  
  sale2 <- sale[date>104]
  date2 <- date[date>104]
  b2 <- sum(sale2*(date2-104-meanX))/SSX
  
  return(b2-b1)
}

```


```{r calculate covid index}
Covid_index <- mydata %>%
              group_by(Item.Number) %>%
              mutate(tot_sale = sum(Bottles.Sold)) %>%
              filter(tot_sale>=730) %>%
              mutate(week = rep(1:209, each=7)[mydate]) %>%
              filter(week < 209) %>%
              ungroup %>%
              group_by(Item.Number, week) %>% 
              mutate(week_s = sum(Bottles.Sold)) %>%
              ungroup %>%
              distinct(Item.Number, week, week_s) %>%
              group_by(Item.Number) %>%
              mutate(Covid_index = mylm(week_s, week)) %>%
              distinct(Item.Number, Covid_index)
```




```{r paralell test}
cl <- makeCluster(20)

stopCluster(cl)
```




